
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.15.0

#include <stan/model/model_header.hpp>

namespace model_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

class model_model : public prob_grad {
private:
    int N;
    vector<double> Y;
    vector<double> m_0x;
    vector<double> m_1x;
    vector<double> A;
    vector<double> p;
public:
    model_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        typedef boost::ecuyer1988 rng_t;
        rng_t base_rng(0);  // 0 seed default
        ctor_body(context__, base_rng, pstream__);
    }

    template <class RNG>
    model_model(stan::io::var_context& context__,
        RNG& base_rng__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, base_rng__, pstream__);
    }

    template <class RNG>
    void ctor_body(stan::io::var_context& context__,
                   RNG& base_rng__,
                   std::ostream* pstream__) {
        current_statement_begin__ = -1;

        static const char* function__ = "model_model_namespace::model_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        context__.validate_dims("data initialization", "N", "int", context__.to_vec());
        N = int(0);
        vals_i__ = context__.vals_i("N");
        pos__ = 0;
        N = vals_i__[pos__++];
        validate_non_negative_index("Y", "N", N);
        context__.validate_dims("data initialization", "Y", "double", context__.to_vec(N));
        validate_non_negative_index("Y", "N", N);
        Y = std::vector<double>(N,double(0));
        vals_r__ = context__.vals_r("Y");
        pos__ = 0;
        size_t Y_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < Y_limit_0__; ++i_0__) {
            Y[i_0__] = vals_r__[pos__++];
        }
        validate_non_negative_index("m_0x", "N", N);
        context__.validate_dims("data initialization", "m_0x", "double", context__.to_vec(N));
        validate_non_negative_index("m_0x", "N", N);
        m_0x = std::vector<double>(N,double(0));
        vals_r__ = context__.vals_r("m_0x");
        pos__ = 0;
        size_t m_0x_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < m_0x_limit_0__; ++i_0__) {
            m_0x[i_0__] = vals_r__[pos__++];
        }
        validate_non_negative_index("m_1x", "N", N);
        context__.validate_dims("data initialization", "m_1x", "double", context__.to_vec(N));
        validate_non_negative_index("m_1x", "N", N);
        m_1x = std::vector<double>(N,double(0));
        vals_r__ = context__.vals_r("m_1x");
        pos__ = 0;
        size_t m_1x_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < m_1x_limit_0__; ++i_0__) {
            m_1x[i_0__] = vals_r__[pos__++];
        }
        validate_non_negative_index("A", "N", N);
        context__.validate_dims("data initialization", "A", "double", context__.to_vec(N));
        validate_non_negative_index("A", "N", N);
        A = std::vector<double>(N,double(0));
        vals_r__ = context__.vals_r("A");
        pos__ = 0;
        size_t A_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < A_limit_0__; ++i_0__) {
            A[i_0__] = vals_r__[pos__++];
        }
        validate_non_negative_index("p", "N", N);
        context__.validate_dims("data initialization", "p", "double", context__.to_vec(N));
        validate_non_negative_index("p", "N", N);
        p = std::vector<double>(N,double(0));
        vals_r__ = context__.vals_r("p");
        pos__ = 0;
        size_t p_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < p_limit_0__; ++i_0__) {
            p[i_0__] = vals_r__[pos__++];
        }

        // validate, data variables
        // initialize data variables

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // validate, set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        ++num_params_r__;
        ++num_params_r__;
        validate_non_negative_index("pm1", "N", N);
        num_params_r__ += N;
        validate_non_negative_index("pm0", "N", N);
        num_params_r__ += N;
    }

    ~model_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("tao")))
            throw std::runtime_error("variable tao missing");
        vals_r__ = context__.vals_r("tao");
        pos__ = 0U;
        context__.validate_dims("initialization", "tao", "double", context__.to_vec());
        // generate_declaration tao
        double tao(0);
        tao = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(tao);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable tao: ") + e.what());
        }

        if (!(context__.contains_r("sigma")))
            throw std::runtime_error("variable sigma missing");
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma", "double", context__.to_vec());
        // generate_declaration sigma
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma: ") + e.what());
        }

        if (!(context__.contains_r("pm1")))
            throw std::runtime_error("variable pm1 missing");
        vals_r__ = context__.vals_r("pm1");
        pos__ = 0U;
        validate_non_negative_index("pm1", "N", N);
        context__.validate_dims("initialization", "pm1", "vector_d", context__.to_vec(N));
        // generate_declaration pm1
        vector_d pm1(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            pm1(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(pm1);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable pm1: ") + e.what());
        }

        if (!(context__.contains_r("pm0")))
            throw std::runtime_error("variable pm0 missing");
        vals_r__ = context__.vals_r("pm0");
        pos__ = 0U;
        validate_non_negative_index("pm0", "N", N);
        context__.validate_dims("initialization", "pm0", "vector_d", context__.to_vec(N));
        // generate_declaration pm0
        vector_d pm0(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            pm0(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(pm0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable pm0: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        T__ tao;
        (void) tao;  // dummy to suppress unused var warning
        if (jacobian__)
            tao = in__.scalar_constrain(lp__);
        else
            tao = in__.scalar_constrain();

        T__ sigma;
        (void) sigma;  // dummy to suppress unused var warning
        if (jacobian__)
            sigma = in__.scalar_lb_constrain(0,lp__);
        else
            sigma = in__.scalar_lb_constrain(0);

        Eigen::Matrix<T__,Eigen::Dynamic,1>  pm1;
        (void) pm1;  // dummy to suppress unused var warning
        if (jacobian__)
            pm1 = in__.vector_constrain(N,lp__);
        else
            pm1 = in__.vector_constrain(N);

        Eigen::Matrix<T__,Eigen::Dynamic,1>  pm0;
        (void) pm0;  // dummy to suppress unused var warning
        if (jacobian__)
            pm0 = in__.vector_constrain(N,lp__);
        else
            pm0 = in__.vector_constrain(N);


        // transformed parameters
        validate_non_negative_index("linpred", "N", N);
        vector<T__> linpred(N);
        stan::math::initialize(linpred, DUMMY_VAR__);
        stan::math::fill(linpred,DUMMY_VAR__);


        try {
            current_statement_begin__ = 17;
            for (int j = 1; j <= N; ++j) {
                current_statement_begin__ = 18;
                stan::math::assign(get_base1_lhs(linpred,j,"linpred",1), ((((get_base1(A,j,"A",1) - get_base1(p,j,"p",1)) * tao) + (get_base1(p,j,"p",1) * get_base1(pm1,j,"pm1",1))) + ((1 - get_base1(p,j,"p",1)) * get_base1(pm0,j,"pm0",1))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        for (int i0__ = 0; i0__ < N; ++i0__) {
            if (stan::math::is_uninitialized(linpred[i0__])) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: linpred" << '[' << i0__ << ']';
                throw std::runtime_error(msg__.str());
            }
        }

        const char* function__ = "validate transformed params";
        (void) function__;  // dummy to suppress unused var warning

        // model body
        try {

            current_statement_begin__ = 21;
            lp_accum__.add(normal_log<propto__>(tao, 0, 10));
            current_statement_begin__ = 22;
            lp_accum__.add(normal_log<propto__>(pm1, m_1x, 10));
            current_statement_begin__ = 23;
            lp_accum__.add(normal_log<propto__>(pm0, m_0x, 10));
            current_statement_begin__ = 24;
            lp_accum__.add(normal_log<propto__>(Y, linpred, sigma));
            current_statement_begin__ = 25;
            lp_accum__.add(cauchy_log<propto__>(sigma, 0, 5));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("tao");
        names__.push_back("sigma");
        names__.push_back("pm1");
        names__.push_back("pm0");
        names__.push_back("linpred");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double tao = in__.scalar_constrain();
        double sigma = in__.scalar_lb_constrain(0);
        vector_d pm1 = in__.vector_constrain(N);
        vector_d pm0 = in__.vector_constrain(N);
        vars__.push_back(tao);
        vars__.push_back(sigma);
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(pm1[k_0__]);
        }
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(pm0[k_0__]);
        }

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        validate_non_negative_index("linpred", "N", N);
        vector<double> linpred(N, 0.0);
        stan::math::initialize(linpred, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(linpred,DUMMY_VAR__);


        try {
            current_statement_begin__ = 17;
            for (int j = 1; j <= N; ++j) {
                current_statement_begin__ = 18;
                stan::math::assign(get_base1_lhs(linpred,j,"linpred",1), ((((get_base1(A,j,"A",1) - get_base1(p,j,"p",1)) * tao) + (get_base1(p,j,"p",1) * get_base1(pm1,j,"pm1",1))) + ((1 - get_base1(p,j,"p",1)) * get_base1(pm0,j,"pm0",1))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters

        // write transformed parameters
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(linpred[k_0__]);
        }

        if (!include_gqs__) return;
        // declare and define generated quantities


        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "tao";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "pm1" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "pm0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "linpred" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "tao";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "pm1" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "pm0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "linpred" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }

}; // model

}




#endif
